variable "name_prefix" {}
variable "subnet_db_1a_id" {}
variable "subnet_db_1b_id" {}
variable "env" {}
variable "db_availability_zones" {}
variable "database_name" {}
variable "db_master_username" {}
variable "db_master_password" {}
variable "db_vpc_security_group_id" {}